#!/usr/bin/env python3
"""Generates a SQL file that brings the `products` table (the database's
copy of the seed catalogue, which supabase/functions/create-payment-intent
prices every real checkout against) back in line with the CATEGORIES array
in src/index.html (what a customer actually sees while browsing).

Why this exists: those are two separate copies of the same base data, kept
in sync by hand rather than by anything mechanical. If a seed product's
price/name/unit/weight/stock is ever edited directly in CATEGORIES (or a
new product added there) without also updating `products` to match, the
two silently drift apart — a customer could see one price while browsing
and be charged a different one at checkout, or a product added only to
CATEGORIES could fail at checkout entirely with "Unknown product" (trusted()
in create-payment-intent requires a `products` row to exist before it even
looks at product_overrides). Run this any time CATEGORIES changes, and run
the SQL it writes before shipping that change — same pattern every other
database change this session has used (no direct DB access from a script
here, so this only ever produces a file for you to run via psql).

Scope: only the seed layer (`products`). custom_products and
product_overrides are untouched — those are already correctly kept live by
the admin panel writing straight to them, this script has nothing to do
with either.

This is NOT wired into the ship workflow the way generate-static-pages.py/
generate-product-pages.py/minify.py are, because — unlike those, which
write local files — this one produces something that has to be run against
the live database by a human with real credentials. Re-run it by hand
whenever CATEGORIES changes.

Usage:
    python3 scripts/sync-products-table.py [output_path]
Defaults to sync_products_table.sql in the repo root if no path is given.
Run from anywhere; paths below are relative to the repo root the script
lives in. Requires `node` on PATH (see generate-product-pages.py's
load_categories(), reused directly here).
"""
import importlib.util
import os
import sys
from datetime import date

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)

# Reuse generate-product-pages.py's load_categories() (which shells out to
# node to safely parse the genuine-JS CATEGORIES literal) instead of
# re-deriving the same parsing here — importing it as a module doesn't run
# its main(), since __name__ won't be '__main__'.
_spec = importlib.util.spec_from_file_location(
    'generate_product_pages', os.path.join(SCRIPT_DIR, 'generate-product-pages.py'))
gpp = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gpp)


def sql_string(s):
    return "'" + s.replace("'", "''") + "'"


def sql_number_or_null(n):
    return 'NULL' if n is None else repr(n) if isinstance(n, float) else str(n)


def build_upsert(cat_slug, idx, p):
    name = sql_string(p['name'])
    unit = sql_string(p['unit'])
    price = sql_number_or_null(p['price'])
    sale_price = sql_number_or_null(p.get('salePrice'))
    weight = sql_number_or_null(p.get('weight'))
    stock = sql_string(p.get('stock') or 'in')
    return (
        f"INSERT INTO public.products (cat_slug, idx, name, unit, price, sale_price, weight, stock)\n"
        f"  VALUES ({sql_string(cat_slug)}, {idx}, {name}, {unit}, {price}, {sale_price}, {weight}, {stock})\n"
        f"  ON CONFLICT (cat_slug, idx) DO UPDATE SET\n"
        f"    name = EXCLUDED.name, unit = EXCLUDED.unit, price = EXCLUDED.price,\n"
        f"    sale_price = EXCLUDED.sale_price, weight = EXCLUDED.weight, stock = EXCLUDED.stock,\n"
        f"    updated_at = now();"
    )


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(REPO_ROOT, 'sync_products_table.sql')

    # load_categories() returns the RAW CATEGORIES array — no
    # custom_products/product_overrides merge here (unlike
    # generate-product-pages.py, which needs the fully-merged view for
    # rendering static pages). Merging those in would be wrong: this
    # script's whole job is syncing the SEED layer only, custom_products
    # and product_overrides already stay correct on their own.
    categories, _code_prefix, _supabase_url, _supabase_anon_key = gpp.load_categories()

    statements = []
    row_count = 0
    for cat in categories:
        cat_slug = cat['slug']
        for idx, p in enumerate(cat['products']):
            statements.append(build_upsert(cat_slug, idx, p))
            row_count += 1

    today = date.today().isoformat()
    header = f"""-- Auto-generated by scripts/sync-products-table.py on {today} —
-- brings the products table's seed layer back in line with the
-- CATEGORIES array in src/index.html as it stood at generation time.
-- Only touches products' own (cat_slug, idx, name, unit, price,
-- sale_price, weight, stock) columns; custom_products and
-- product_overrides are untouched. Safe to re-run: every statement is
-- an upsert keyed on the real primary key (cat_slug, idx).
--
-- {row_count} seed products from CATEGORIES.

BEGIN;

"""
    footer = "\nCOMMIT;\n"

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(header)
        f.write('\n\n'.join(statements))
        f.write(footer)

    print(f'wrote {out_path} ({row_count} seed products, {os.path.getsize(out_path):,} bytes)')


if __name__ == '__main__':
    main()
